-- MySQL initialization script for EVService
-- This script prepares schema and settings; Spring JPA (ddl-auto=update) will create/upgrade tables.

-- Ensure UTF8MB4 and sane SQL mode
SET NAMES utf8mb4;
SET @@session.sql_mode = REPLACE(@@session.sql_mode,'ONLY_FULL_GROUP_BY','');

-- Create database if not exists (docker-compose already creates it, but keep idempotent)
CREATE DATABASE IF NOT EXISTS evservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE evservice;

-- Optional: create application user (compose creates too)
-- CREATE USER IF NOT EXISTS 'evuser'@'%' IDENTIFIED BY 'evpass';
-- GRANT ALL PRIVILEGES ON evservice.* TO 'evuser'@'%';
-- FLUSH PRIVILEGES;

-- Seed minimal lookup data can be inserted after JPA creates tables.
-- You can place additional seed scripts that run after first app start.

-- End of init (tables will be generated by Hibernate)